### GET hello
GET http://localhost:8888/hello

### GET gw 1
GET http://localhost:8888/gw

### GET gw 2
GET http://localhost:8888/ga/aaa

### POST gw
POST http://localhost:8888/ga/cn.william.wmrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"cn.william.wmrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}